config/routes.rb
Rails.application.routes.draw do

  get 'tournaments/new'

  root 'tournaments#new'

  resources :tournaments
  resources :players
  resources :matches

  get 'tournaments/:id/build_tournament', to: 'tournaments#build_tournament'
  post 'tournaments/:id/build_tournament', to: 'tournaments#build_tournament'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord

  belongs_to :player_one, class_name: 'Player', optional: true
  belongs_to :player_two, class_name: 'Player', optional: true
  belongs_to :winner, class_name: 'Player', optional: true
  belongs_to :round

  def update_results(p1_score, p2_score)
    results = calculate_results(p1_score, p2_score)
    results[:winner].update_win_count
    results.each { |position, player| player.update_stats }
    self.update_attributes(winner: results[:winner], p1_score: p1_score, p2_score: p2_score)
  end

  def win_by_bye
    self.update_attributes(winner: player_one)
  end

  def player_type
    bye == true ? "B Y E" : "P L A Y E R"
  end

  private

  def calculate_results(p1_score, p2_score)
    p1_score > p2_score ? {winner: player_one, loser: player_two} : {winner: player_two, loser: player_one}
  end
end

app/models/player.rb
class Player < ApplicationRecord

  has_many :tournament_players
  has_many :tournaments, through: :tournament_players

  def update_stats
    update_attributes(games: update_games_count, win_percentage: calculate_win_percentage)
  end

  def update_win_count
    self.wins += 1
  end

  def update_games_count
    self.games += 1
  end

  def calculate_win_percentage
    (wins.to_f/games) * 100
  end
end

app/models/round.rb
class Round < ApplicationRecord

  has_many :matches
  belongs_to :tournament

  def is_final?
    self.matches.length < 2
  end

  def collect_winners
    matches.map { |match| match.winner }
  end

  def update_byes
    matches.each do |match|
      if match.bye == true
        match.win_by_bye
      end
    end
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord

  has_many :tournament_players
  has_many :rounds
  has_many :players, through: :tournament_players

  def build_tournament
    create_first_round
    create_remaining_rounds
    update_byes
  end

  def process_results(round)
    current_round = rounds.find(round)
    update_next_round(current_round) unless current_round.is_final?
  end

  def champion
    final_winner = rounds.last.matches[0].winner
    final_winner ? final_winner.name : nil
  end

  private

  def create_first_round
    byes_array = []
    byes_count.times do
      byes_array << :bye
    end
    players_and_byes = players.zip(byes_array).flatten.compact
    pairings = create_pairings(players_and_byes)
    first_round = rounds.build
    first_round_matches = pairings.map do |pair|
      if pair.any? { |player| player == :bye }
        first_round.matches << Match.create(player_one: pair[0], bye: true)
      else
        first_round.matches << Match.create(player_one: pair[0], player_two: pair[1])
      end
    end
    first_round.save
    rounds << first_round
  end

  def create_remaining_rounds
    count = rounds.first.matches.size
    p count
    while count >= 2
      count /= 2
      p count
      next_round = rounds.build
      next_round.save
      count.times do
        match = next_round.matches.build
        match.save
        next_round.matches << match
      end
      rounds << next_round
    end
  end

  def update_next_round(round)
    pairings = create_pairings(round.collect_winners)
    next_round = rounds.find(round.id+1)
    next_round.matches.map.with_index do |match, i|
      match.player_one = pairings[i][0]
      match.player_two = pairings[i][1]
      match.save
    end
    next_round.save
  end

  def create_pairings(collection)
    collection.each_slice(2).to_a
  end

  def collect_winners(round)
    currentround = rounds.find(round)
    pairings = create_pairings(current_round.collect_winners)
  end

  def byes_count
    player_count = players.size
    powers_array = []
    2.upto(10) { |p| powers_array << 2**(p-1) }
    tournament_size = powers_array.find { |x| x >= player_count }
    tournament_size - player_count
  end

  def update_byes
    rounds.first.update_byes
  end
end

app/models/tournament_player.rb
class TournamentPlayer < ApplicationRecord

  belongs_to :player
  belongs_to :tournament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def create
    @match = Match.new(tournament_params)
    @match.save
  end

  def update
    @match = Match.find(params[:id])
    @match.update_results(params[:match][:p1_score], params[:match][:p2_score])
    @tournament = Tournament.find(params[:match][:tournament_id])
    @tournament.process_results(@match.round_id)
    redirect_to(@tournament)
  end

  private

  def match_params
    params.require(:match).permit(:player_one_id, :player_two_id, :round_id, :p1_score, :p2_score, :winner, :bye)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
  end

  def new
  end

  def create
    @tournament = Tournament.find(params[:player][:tournament_id])
    @tournament.players.create(player_params)
    redirect_to(:back)
  end

  private

  def player_params
    params.require(:player).permit(:name, :wins, :games, :win_percentage)
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def index
    @tournaments = Tournament.all
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.save
    redirect_to @tournament
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def update
    @tournament = Tournament.find(params[:id])
    @player = Player.find(params[:tournament][:players])
    @tournament.players << @player
    @tournament.save
    redirect_to @tournament
  end

  def build_tournament
    @tournament = Tournament.find(params[:id])
    @tournament.build_tournament
    redirect_to @tournament
  end

  private

  def tournament_params
    params.require(:tournament).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tournament_helper.rb
module TournamentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forrest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<ul>
<% @players.map do |player| %>
  <li><%= player.name %> | win percentage: <%= number_to_percentage(player.win_percentage, precision: 0) %></li>
<% end %>
</ul>

app/views/tournaments/new.html.erb
<h1>Create a new tournament</h1>
<%= form_for :tournament, url: tournaments_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tournaments/show.html.erb
<h1><%= @tournament.name %></h1>

<% if @tournament.rounds.empty? %>

  <ul>
    <% @tournament.players.map do |player| %>
      <li><%= player.name %></li>
    <% end %>
  </ul>

  <h3>Add new player</h3>
  <%= form_for :player, url: players_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <%= f.hidden_field :tournament_id, value: @tournament.id %>
      <%= f.submit "Add to Tournament" %>
    </p>
  <% end %>

  <h3>Add existing player</h3>
  <%= form_for @tournament do |f| %>
    <p>
      <%= f.collection_select(:players, Player.all, :id, :name) %>
      <%= f.submit "Add to Tournament" %>
    </p>
  <% end %>

  <%= button_to "Generate Matches", action: :build_tournament %>

<% else %>

  <% @tournament.rounds.map.with_index do |round, i| %>
    <h1><%= "Round #{i+1}" %></h1>
    <% round.matches.map do |match| %>
      <h2>Match:</h2>
      <h3>p1:<%= match.player_one ? match.player_one.name : "P L A Y E R" %></h3>
      <h3>p2:<%= match.player_two ? match.player_two.name : match.player_type %></h3>
      <% if match.winner %>
        <h3>Winner: <%= match.winner.name %></h3>
      <% else %>
        <%= form_for match do |f| %>
          <p>
            <%= f.label :p1_score %>
            <%= f.text_field :p1_score %>
            <%= f.label :p2_score %>
            <%= f.text_field :p2_score %>
            <%= f.hidden_field :tournament_id, value: @tournament.id %>
          </p>
          <p>
            <%= f.submit %>
          </p>
        <% end %>
      <% end %>
      <% if round.is_final? %>
        <h1>Champion: <%= @tournament.champion %></h1>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<% console %>